### ISSUE TITLE
Implementar clases asignadas.

### ISSUE THREAD

**Issue by 7JuanBautistaPolo** [7JuanBautistaPolo/Mi-primer-repositorio-G59#11]
- Implementar clases asignadas

**Comment by julrodrig** [comment]
**PERSONA** 

{
    /// <summary>Class <c>Persona</c>
    /// Modela una Persona en general en el sistema
    /// </summary>
    public class Persona
    {
    // Identificador único de cada persona
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string NumeroTelefono { get; set; }
		public string Email { get; set; }
	    public string UsuarioWeb { get; set; }
		public string PasswordWeb { get; set; }
    }
}



**PERSONAL TECNICO**

{
	/// <summary>Class <c>Profesional Técnico</c>
	/// Modela un Personal Tecnico
	/// </summary>
	public class ProfesionalTecnico : Persona
	{
	/// Numero de Registro del Técnico
	public string NumeroRegistroProfesional { get; set; }
	/// Nivel de Estudios de Tecnico 
	public string NivelEstudios { get; set; }
	}
}
