### ISSUE TITLE
Definir lineamientos para el código.

### ISSUE THREAD

**Issue by 7JuanBautistaPolo** [7JuanBautistaPolo/Mi-primer-repositorio-G59#12]
- Definir lineamientos para el código (estándares del equipo).
- Integrar clases.
- Generar migraciones.

**Comment by RonnySerrano** [comment]
[Lineamientos del Código.docx](https://github.com/7JuanBautistaPolo/Mi-primer-repositorio-G59/files/9457154/Lineamientos.del.Codigo.docx)
