### ISSUE TITLE
Hacer listado de pruebas básicas.

### ISSUE THREAD

**Issue by 7JuanBautistaPolo** [7JuanBautistaPolo/Mi-primer-repositorio-G59#14]
- Hacer listado de pruebas básicas para el siguiente sprint.
- Implementar clases asignadas.
- Verificar la conexión y generación de tablas.

**Comment by oeg8090** [comment]
Lista básica de revisión.
1.	revisar la estructura del proyecto.
2.	garantizar que en las carpetas necesarias el proyecto estén creadas y en la ubicación correcta.
3.	Revisar que las clases hayan sido creadas.
4.	revisar los nombres de las clases concuerden con en diagrama de entidad.
5.	Inspeccionar que en las relaciones entre las diferentes carpetas se hallan implementado.
6.	Revisar que se hallan instalado los complementos necesarios dentro de los archivos CSproj.
7.	Ejecutar compilación para comprobar si hay algún error.
8.	Revisar dentro de la carpeta persistencia sí se creó carpeta migración.
9.	Revisar dentro del archivo AppContext si esta referenciar las entidades qué queremos mapear, al igual que los datos de conexión a la base de datos sean correctos.
10.	Dentro del gestor de base de datos en nuestro caso azure data studio buscar sin la base de datos implementada se mapeo correctamente con las tablas necesarias.
11.	implementar los métodos dentro del proyecto para probar sí se puede interactuar con las diferentes tablas en la base de datos.
